apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-redis-deployment
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-redis
  template:
    metadata:
      labels:
        app: node-redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
          - containerPort: 6379
          volumeMounts:
          - mountPath: /srv/www
            name: redis-storage
        - name: node-redis
          image: wberilo/cacheserver
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
          ports:
        - containerPort: 3000
      volumes:
      - name: redis-storage
        emptyDir: {}


