apiVersion: v1
kind: Service
metadata:
  name: node-mongo-service
  namespace: app-namespace
spec:
  selector:
    app: node-mongo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
