apiVersion: apps/v1
kind: Deployment
metadata:
  name: svelte-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: svelte-app
  template:
    metadata:
      labels:
        app: svelte-app
    spec:
      containers:
        - name: svelte-app-container
          image: yourdockerhubusername/svelte-app:latest
          ports:
            - containerPort: 5173
